"""add profile_photo_url to reivews

Revision ID: 643787fd2f69
Revises: 82d2f110cf08
Create Date: 2025-02-14 22:21:38.767332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643787fd2f69'
down_revision: Union[str, None] = '82d2f110cf08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('profile_photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'profile_photo_url')
    # ### end Alembic commands ###
