"""add place_id (properly) to reviews table

Revision ID: 82d2f110cf08
Revises: 6ffcc02a071e
Create Date: 2025-02-14 22:16:47.028583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d2f110cf08'
down_revision: Union[str, None] = '6ffcc02a071e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('place_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_reviews_place_id'), 'reviews', ['place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_place_id'), table_name='reviews')
    op.drop_column('reviews', 'place_id')
    # ### end Alembic commands ###
