"""add_business_selection

Revision ID: bca0d0b33e91
Revises: b3533bf3c630
Create Date: 2025-02-13 18:45:22.230119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca0d0b33e91'
down_revision: Union[str, None] = 'b3533bf3c630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embed_snippets', sa.Column('font_family', sa.String(), nullable=True))
    op.add_column('embed_snippets', sa.Column('text_color', sa.String(), nullable=True))
    op.add_column('embed_snippets', sa.Column('star_color', sa.String(), nullable=True))
    op.add_column('embed_snippets', sa.Column('text_size', sa.String(), nullable=True))
    op.add_column('embed_snippets', sa.Column('container_width', sa.String(), nullable=True))
    op.add_column('embed_snippets', sa.Column('reviews_per_row', sa.Integer(), nullable=True))
    op.drop_constraint('embed_snippets_business_url_key', 'embed_snippets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('embed_snippets_business_url_key', 'embed_snippets', ['business_url'])
    op.drop_column('embed_snippets', 'reviews_per_row')
    op.drop_column('embed_snippets', 'container_width')
    op.drop_column('embed_snippets', 'text_size')
    op.drop_column('embed_snippets', 'star_color')
    op.drop_column('embed_snippets', 'text_color')
    op.drop_column('embed_snippets', 'font_family')
    # ### end Alembic commands ###
